name: turbots
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_database: ^11.1.6
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7
  firebase_crashlytics: ^4.1.4
  
  # State Management
  flutter_riverpod: ^2.4.9
  provider: ^6.1.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Networking
  connectivity_plus: ^5.0.2
  http: ^1.1.0
  
  # UI/UX
  cupertino_icons: ^1.0.6
  fl_chart: ^0.69.2
  
  # Utilities
  pdf: ^3.10.7
  printing: ^5.12.0
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  intl: ^0.18.1
  excel: ^4.0.0
  mailer: ^6.0.1
  flutter_dotenv: ^5.1.0
  file_picker: ^8.1.4
  
  # Logging & Analytics
  device_info_plus: ^10.1.0
  package_info_plus: ^8.3.1
  logger: ^2.0.2+1

  # Routing
  go_router: ^12.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    # Logo file
    - assets/logos/turbo_air_logo.png
    # Include all screenshots subdirectories
    - assets/screenshots/