// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByN2I4vjSQO2ptsj8mbkbsqvu94HOtp8c',
    appId: '1:118954210086:web:c1bfc8c90049145bb187e7',
    messagingSenderId: '118954210086',
    projectId: 'turbo-air-viewer',
    authDomain: 'turbo-air-viewer.firebaseapp.com',
    storageBucket: 'turbo-air-viewer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGeAvfO35-KL0r1UhfzykfGtNeeuK5dyY',
    appId: '1:118954210086:android:5fa61a986163fcd9b187e7',
    messagingSenderId: '118954210086',
    projectId: 'turbo-air-viewer',
    storageBucket: 'turbo-air-viewer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVCBIzycrcpYxPTqRkSegLrrfqYO8xF5A',
    appId: '1:118954210086:ios:22326e13f6d3b762b187e7',
    messagingSenderId: '118954210086',
    projectId: 'turbo-air-viewer',
    storageBucket: 'turbo-air-viewer.firebasestorage.app',
    iosBundleId: 'com.turboair.turboAir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByN2I4vjSQO2ptsj8mbkbsqvu94HOtp8c',
    appId: '1:118954210086:web:b44c8afb0d9cb19cb187e7',
    messagingSenderId: '118954210086',
    projectId: 'turbo-air-viewer',
    authDomain: 'turbo-air-viewer.firebaseapp.com',
    storageBucket: 'turbo-air-viewer.firebasestorage.app',
  );

}