// Location: lib/main.dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart' as fb;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'core/services/offline_service.dart';
import 'app.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive for local storage
  await Hive.initFlutter();

  try {
    // Initialize Firebase
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    // Debug authentication state changes
    fb.FirebaseAuth.instance.authStateChanges().listen((fb.User? user) {
      if (user == null) {
        print('🔴 User is currently signed out!');
      } else {
        print('🟢 User is signed in: ${user.email}');
      }
    });

    // Optional: Enable Firestore offline persistence
    FirebaseFirestore.instance.settings = const Settings(
      persistenceEnabled: true,
      cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
    );

    // Optional: Set up Firebase Crashlytics
    FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;

    // Initialize Supabase
    await Supabase.initialize(
      url: 'https://lxaritlhujdevalclhfc.supabase.co',
      anonKey:
          'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4YXJpdGxodWpkZXZhbGNsaGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzOTg4NTIsImV4cCI6MjA2ODk3NDg1Mn0.2rapqW5LdMO9s4JeQOsuiqzfDmIcvvQT8OYDkA3albc',
    );

    // Register Hive adapters (simplified without code generation)
    await OfflineService.registerAdapters();

    // Initialize offline storage
    await OfflineService.initialize();

    // Check if user is logged in (Firebase first, then Supabase)
    final fb.User? firebaseUser = fb.FirebaseAuth.instance.currentUser;
    if (firebaseUser != null) {
      debugPrint('Firebase user already logged in: ${firebaseUser.email}');
    }

    final supabaseUser = Supabase.instance.client.auth.currentUser;
    if (supabaseUser != null) {
      debugPrint('Supabase user already logged in: ${supabaseUser.email}');
    }

    runApp(
      const ProviderScope(
        child: TurboAirApp(),
      ),
    );
  } catch (e) {
    debugPrint('❌ Initialization error: $e');

    // Show error UI if initialization fails
    runApp(ConfigErrorApp(error: e.toString()));
  }
}

// Error app to show when configuration is missing or initialization fails
class ConfigErrorApp extends StatelessWidget {
  final String? error;

  const ConfigErrorApp({super.key, this.error});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: const Color(0xFF20429C),
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(24.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Icon(
                  Icons.warning_amber_rounded,
                  size: 80,
                  color: Colors.white,
                ),
                const SizedBox(height: 24),
                const Text(
                  'Configuration Error',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 16),
                Text(
                  error != null
                      ? 'Initialization failed:\n$error'
                      : 'Configuration not found.\nPlease check Firebase and Supabase setup.',
                  style: const TextStyle(color: Colors.white70, fontSize: 16),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 24),
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Colors.black26,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: const Text(
                    'Steps to fix:\n'
                    '1. Run: flutterfire configure (for Firebase)\n'
                    '2. Verify Supabase credentials are correct\n'
                    '3. Check internet connection\n'
                    '4. Run: flutter pub get\n'
                    '5. Restart the app',
                    style: TextStyle(
                      color: Colors.white,
                      fontFamily: 'monospace',
                      fontSize: 12,
                    ),
                  ),
                ),
                const SizedBox(height: 16),
                ElevatedButton(
                  onPressed: () {
                    // Attempt to restart (won't actually work, just for UX)
                    debugPrint('User requested restart');
                  },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.white,
                    foregroundColor: const Color(0xFF20429C),
                  ),
                  child: const Text('Retry'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
